### ISSUE TITLE
Windows 10 installation error

### ISSUE THREAD

**Issue by Daivy03** [BattleDash/DungeonsRPC#1]
After doing **npm install** in the program directory I see a lot of errors. (See screenshot below)
I don't know ho to fix it. 

![image](https://user-images.githubusercontent.com/75785698/123556983-8ca6c680-d78e-11eb-8e21-d0c3864cb130.png)

**EDIT:**
I found the solution to remove some errors. Git Bash for windows 10 needs to be installed

**Comment by battledash** [comment]
I wouldn't recommend using this, I haven't updated it in years and you'll most likely just brick your game and have to reset the hosts file.
